parameters:
  - name: env
    type: string
  - name: mainProductName
    type: string
  - name: resourceGroupTypeName
    type: string
    default: rg
  - name: functionsTypeName
    type: string
    default: func
  - name: vnetTypeName
    type: string
    default: vnet
  - name: subnetTypeName
    type: string
    default: subnet

variables:
  - name: env
    value: ${{ parameters.env }}
  - name: varOrg
    value: myorg
  - name: varSubscriptions
    value: "ci, t1, t2, t3: myorg-devtest-subscription; a1, a2, p1, p2, p3: myorg-production-subscription"
  - name: varNameFormat
    value: "{org}-{env}-{product}-{type}"
  - name: varResourceGroupTypeName
    value: ${{ parameters.resourceGroupTypeName }}
  - name: varFunctionsTypeName
    value: ${{ parameters.functionsTypeName }}
  - name: varVnetTypeName
    value: ${{ parameters.vnetTypeName }}
  - name: varSubnetTypeName
    value: ${{ parameters.subnetTypeName }}
  - name: varMainProductName
    value: ${{ parameters.mainProductName }}
